<?php
$data = $block->getRoomInfo();
?>

<form name="form_staff_registry" method="post" action= <?php echo $block->myUrl() ?>>
    <input hidden="true" type="text" name="id" value= <?php echo $data["id"] ?>>
    <span> Name</span>
    <input type="text" disabled="true" value="<?php echo($data["name"]) ?>">
    <span> Price</span>
    <input type="number" disabled="true" value="<?php echo $data["price"] ?>">
    <span> Number PC</span>
    <input type="number" name="number_pc" value="<?php echo $data["number_pc"] ?>">
    <span> Address</span>
    <input type="text" name="address" value="<?php echo $data["address"] ?>">
    <span> Food Price</span>
    <input type="number" name="food_price" value= "<?php echo $data["food_price"] ?>">
    <span> Drink Price</span>
    <input type="number" name="drink_price" value= "<?php echo $data["drink_price"] ?>">
    <input type="number" name="product_id" hidden="hidden" value= "<?php echo $data["product_id"] ?>">
    <input type="submit">
</form>






