<?php
$arrayData = $block->getRoomInfo();
$isManager = $block->isManager();
?>

<table>
    <tr>
        <th>Product ID</th>
        <th>Room name</th>
        <th>Price</th>
        <th>Action</th>
    </tr>
    <?php
    if (!empty($arrayData)) {
        foreach ($arrayData as $row) {
            if($isManager == 1)
            {
                echo "<tr>
                    <td>" . $row["product_id"] . "</td>
                    <td>" . $row["name"] . "</td>
                    <td>" . $row["price"] . "</td>
                    <td>" . $row["address"] . "</td>
                    <td class='action'>
                       <a href=" . $block->myUrl($row["id"]) . "
                       id = " . 'edit' . $row["id"] . ">Edit</a> 
                    </td>
                  </tr>";
            }
            else{
                echo "<tr>
                    <td>" . $row["product_id"] . "</td>
                    <td>" . $row["name"] . "</td>
                    <td>" . $row["price"] . "</td>
                    <td>
                       <a style='pointer-events: none; color: #EBEBE4'>Edit</a> 
                    </td>
                  </tr>";
            }
        }
    }
    ?>
</table>


