<?php
namespace Magenest\Cybergame\Model;
class RoomExtraOption extends
    \Magento\Framework\Model\AbstractModel {
    public function _construct() {
        $this->_init('Magenest\Cybergame\Model\ResourceModel\RoomExtraOption');
    }

    public function __call($method, $args)
    {
        return parent::__call($method, $args); // TODO: Change the autogenerated stub
    }
}